name: Check Markdown links

on:
  pull_request:
      branches: [main]
  push:
      branches: [main]


jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        file-extension: .md .mdx
